import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import type { OutputAsset, OutputChunk } from "rollup";
import { defineConfig, type Plugin } from "vitest/config";

const STATIC_SHELL_FILES = [
  "manifest.webmanifest",
  "icons/app-icon.svg",
  "models/silero-vad-v6.2.1/silero_vad_16k_op15.onnx",
  "models/silero-vad-v6.2.1/LICENSE.upstream.txt",
  "models/silero-vad-v6.2.1/README.txt",
  "runtime/onnxruntime-web-1.29.0/LICENSE.upstream.txt",
  "runtime/onnxruntime-web-1.29.0/ThirdPartyNotices.upstream.txt",
  "runtime/onnxruntime-web-1.29.0/README.txt",
] as const;

function serviceWorkerSource(
  releaseId: string,
  files: readonly string[],
): string {
  return `/* Generated by the Vite build. Do not edit this file directly. */
const RELEASE_ID = ${JSON.stringify(releaseId)};
const APP_BASE = new URL("./", self.registration.scope);
const SCOPE_ID = encodeURIComponent(self.registration.scope);
const CACHE_PREFIX = "cinematic-audio-shell-" + SCOPE_ID + "-";
const SHELL_CACHE = CACHE_PREFIX + RELEASE_ID;
const PRECACHE_URLS = ${JSON.stringify(files)}.map((path) => new URL(path, APP_BASE).href);
const PRECACHE_BY_PATH = new Map(PRECACHE_URLS.map((url) => [new URL(url).pathname, url]));
const NAVIGATION_FALLBACK = new URL("index.html", APP_BASE).href;

function shellFailure(status, code, detail) {
  return new Response(detail, {
    status,
    headers: { "Content-Type": "text/plain; charset=utf-8", "X-Audio-PWA-Shell-Error": code },
  });
}

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(SHELL_CACHE).then((cache) => cache.addAll(PRECACHE_URLS)));
});

self.addEventListener("activate", (event) => {
  // The browser only activates this worker after the previous worker has no clients.
  // We intentionally do not call skipWaiting() or clients.claim(): old pages keep the
  // worker and cache version that loaded them until their next navigation.
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(
        keys
          .filter((key) => key.startsWith(CACHE_PREFIX) && key !== SHELL_CACHE)
          .map((key) => caches.delete(key)),
      ),
    ),
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  const url = new URL(request.url);
  if (request.method !== "GET" || url.origin !== self.location.origin) return;

  if (request.mode === "navigate" && url.pathname.startsWith(APP_BASE.pathname)) {
    event.respondWith(
      (async () => {
        const cache = await caches.open(SHELL_CACHE);
        const cachedDocument = await cache.match(NAVIGATION_FALLBACK);
        if (cachedDocument) return cachedDocument;
        return self.navigator.onLine === false
          ? shellFailure(503, "offline-document-missing", "The offline application document is missing.")
          : shellFailure(503, "controller-document-missing", "This controller's application document is missing. Close all app tabs and reload to recover safely.");
      })(),
    );
    return;
  }

  const canonicalAssetUrl = PRECACHE_BY_PATH.get(url.pathname);
  if (!canonicalAssetUrl) return;
  event.respondWith(
    (async () => {
      const cache = await caches.open(SHELL_CACHE);
      const cachedAsset = await cache.match(canonicalAssetUrl);
      if (cachedAsset) return cachedAsset;
      if (self.navigator.onLine === false) {
        return shellFailure(503, "offline-asset-missing", "A required offline application asset is missing.");
      }
      try {
        const response = await fetch(canonicalAssetUrl, { credentials: "same-origin" });
        return response.ok
          ? response
          : shellFailure(502, "online-asset-unavailable", "A required application asset is unavailable from the server.");
      } catch {
        return shellFailure(504, "asset-network-failure", "A required application asset could not be loaded from the network.");
      }
    })(),
  );
});

self.addEventListener("message", (event) => {
  if (event.data?.type !== "CHECK_SHELL") return;
  event.waitUntil(
    caches.open(SHELL_CACHE).then(async (cache) => {
      const entries = await Promise.all(PRECACHE_URLS.map((url) => cache.match(url)));
      event.ports[0]?.postMessage({
        type: "SHELL_STATUS",
        releaseId: RELEASE_ID,
        ready: entries.every(Boolean),
        cachedAssets: entries.filter(Boolean).length,
        requiredAssets: PRECACHE_URLS.length,
      });
    }),
  );
});
`;
}

function immutableShellPlugin(): Plugin {
  return {
    name: "immutable-shell-service-worker",
    apply: "build",
    generateBundle(_options, bundle) {
      const generatedFiles = Object.values(bundle)
        .filter(
          (entry): entry is OutputAsset | OutputChunk =>
            entry.fileName !== "service-worker.js",
        )
        .map((entry) => entry.fileName)
        .filter(
          (fileName) =>
            fileName === "index.html" ||
            (fileName.startsWith("assets/") &&
              (fileName.endsWith(".js") ||
                fileName.endsWith(".css") ||
                fileName.endsWith(".wasm"))),
        );
      const shellFiles = [
        "./",
        "index.html",
        ...generatedFiles,
        ...STATIC_SHELL_FILES,
      ]
        .map((fileName) =>
          fileName.startsWith("./") ? fileName : `./${fileName}`,
        )
        .sort();
      const releaseHash = createHash("sha256");
      for (const entry of Object.values(bundle)) {
        releaseHash.update(entry.fileName);
        releaseHash.update(
          entry.type === "chunk" ? entry.code : String(entry.source),
        );
      }
      for (const fileName of STATIC_SHELL_FILES) {
        releaseHash.update(fileName);
        releaseHash.update(
          readFileSync(new URL(`./public/${fileName}`, import.meta.url)),
        );
      }
      const releaseId = releaseHash.digest("hex").slice(0, 16);

      this.emitFile({
        type: "asset",
        fileName: "service-worker.js",
        source: serviceWorkerSource(releaseId, shellFiles),
      });
    },
  };
}

export default defineConfig({
  base: "./",
  plugins: [immutableShellPlugin()],
  build: {
    target: "es2022",
    sourcemap: true,
  },
  worker: {
    format: "es",
  },
  test: {
    environment: "node",
    include: ["src/**/*.test.ts"],
  },
});
